### ISSUE TITLE
推荐“前端早读课”

### ISSUE THREAD

**Issue by Lionad-Morotar** [fz6m/weixin-fe#1]
* [前端早读课](https://weixin.sogou.com/weixin?type=1&s_from=input&query=%E5%89%8D%E7%AB%AF%E6%97%A9%E8%AF%BB%E8%AF%BE)

---

搜狗能搜到公众号的二维码和最近更新文章，可以写一个爬虫放到 github actions 里，一来方便在 Readme 中增加一些供参考的信息，二来是每日定期抓最新文章，以便灵活排序。

**Comment by fz6m** [comment]
已更新
